#pragma once

namespace Event
{
    enum class Event
    {
        StartGame,

        MajorKeyBailey,
        MajorKeyUnderbelly,
        MajorKeyTower,
        MajorKeyKeep,
        MajorKeyTheatre,

        SmallKeyDungeonRafters,
        SmallKeyDungeonStrongEyes,
        SmallKeyCastleCrossroads,
        SmallKeyCastleTallRoom,
        SmallKeyUnderbellyBigRoom,
        SmallKeyKeepLeverRoom,
        SmallKeyBaileyBuilding,

        HealthPieceLibraryBack,
        HealthPieceLibraryLocked,
        HealthPieceCastleCorner,
        HealthPieceCastleBalcony,
        HealthPieceCastleCrawlers,
        HealthPieceCastleScythes,
        HealthPieceCastleRiver,
        HealthPieceBaileySteeple,
        HealthPieceKeepLocked,
        HealthPieceUnderbellyRafters,
        HealthPieceUnderbellyPillar,
        HealthPieceUnderbellyBuilding,
        HealthPieceTheatreAuditorium,
        HealthPieceTheatreBoxes,
        HealthPieceDungeonAlcove,
        HealthPieceDungeonPoles,

        AbilityDreamBreaker,
        AbilityIndignation,
        AbilitySlide,
        AbilitySolarWind,
        AbilitySunGreaves,
        AbilitySunsetter,
        AbilityClingGem,
        AbilityAscendantLight,
        AbilityStrikebreak,
        AbilitySoulCutter,

        AspectClearMindLibrary,
        AspectClearMindKeep,
        AspectClearMindCastle,
        AspectEmpathyBailey,
        AspectEmpathyTheatre,
        AspectGoodGracesCastle,
        AspectGoodGracesDungeon,
        AspectMartialProwess,
        AspectPilgrimage,
        AspectAerialFinesse,
        AspectHeliacalPower,

        Memento,

        AttireProfessionalism,
        AttireAGuardian,
        AttireChivalry,
        AttireBleedingHeart,
        AttireNostalgia,
        AttireDevotion,
        AttireClass,
        AttireSweater,

        TransitionDungeonToCastle,
        TransitionDungeonToUnderbelly,
        TransitionDungeonToTheatre,
        TransitionCastleToDungeon,
        TransitionCastleToBailey,
        TransitionCastleToKeepSouth,
        TransitionCastleToKeepLocked,
        TransitionCastleToKeepNorth,
        TransitionCastleToLibrary,
        TransitionCastleToTheatrePillar,
        TransitionCastleToTheatreFront,
        TransitionLibraryToCastle,
        TransitionBaileyToCastle,
        TransitionBaileyToUnderbelly,
        TransitionBaileyToTower,
        TransitionBaileyToTheatre,
        TransitionKeepToCastleSouth,
        TransitionKeepToCastleLocked,
        TransitionKeepToCastleNorth,
        TransitionKeepToUnderbelly,
        TransitionKeepToTheatre,
        TransitionUnderbellyToDungeon,
        TransitionUnderbellyToBailey,
        TransitionUnderbellyToKeep,
        TransitionTheatreToDungeon,
        TransitionTheatreToCastleWest,
        TransitionTheatreToCastleNorthwest,
        TransitionTheatreToBailey,
        TransitionTheatreToKeep,
        TransitionTowerToBailey,
        TransitionTowerToChambers,
        TransitionChambersToTower,

        FinishGame,
    };

    void Triggered(Event);
}
